[build]
target = "bootloader_config.json"

rustflags = ["-Z", "thinlto=off", "-C", "relocation-model=static", "-C", "link-arg=-Tlink.x"]
#"-C", "link-args=/entry:entry /subsystem:native /base:0xf000 /fixed /debug /nodefaultli"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

