[build]
target = "bootloader_config.json"

rustflags = ["-Z", "thinlto=off", "-C", "relocation-model=static", "-C", "link-arg=-Tlink.x"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

